#!/bin/bash

################################################################################
#                                                                              #
# A hook into torctl to enable the use of bridges.                             #
#                                                                              #
# AUTHORS                                                                      #
# https://github.com/Al-Pharaday                                               #
# https://github.com/Nespelem-3000                                             #
#                                                                              #
################################################################################

declare -A BRIDGES=(
            ["file"]="/usr/etc/torctl/bridges.txt"
            ["list"]=""
        )

list() {
sed -i '/^\s*$/d' ${BRIDGES["file"]}
while IFS="" read -r p || [ -n "$p" ]
do
  printf '%s\n' "Bridge $p"
done <${BRIDGES["file"]}
}

conf_bridges() {
    if [ ! -e ${BRIDGES["file"]} ]; then
        warn "${BRIDGES["file"]} file not found"
        info "creating ${BRIDGES["file"]}"
        touch ${BRIDGES["file"]}
        msg "${BRIDGES["file"]} created"
    fi

    if [ ! -e "/usr/bin/obfs4proxy" ]; then
        warn "Install obfs4proxy <pacman -S obfs4proxy> to be able to use obfs4 as a pluggable transport, and/or webtunnel <https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/webtunnel> to be able to use webtunnel as a pluggable transport."
    fi    

    if [ -s ${BRIDGES["file"]} ]; then
        #BRIDGES["list"]=$(cat ${BRIDGES["file"]})
        info "using provided bridge"
        USE_BRIDGES=$(echo -e "#Bridges\nUseBridges 1\n$(list)\nClientTransportPlugin obfs4 exec /usr/bin/obfs4proxy\nClientTransportPlugin webtunnel exec /usr/bin/webtunnel")
    else
        warn "${BRIDGES["file"]} file is empty. For now no bridges will be used."
        warn "Insert your bridges in ${BRIDGES["file"]} one per line."
    fi
}
